In [1]:
#import numpy
import numpy as np

In [23]:
#checking the datatype of an array
arr = np.array([10,20,30,40,50])
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [24]:
#cheacking numpy version 
print(np.__version__)

1.26.4


In [25]:
#list
list=[1,2,3,4,5]
print(list)

[1, 2, 3, 4, 5]


In [26]:
#0D array
arr=np.array(43)
print(arr)
print(arr.ndim)

43
0


In [27]:
#1D array
arr=np.array([10,20,30,40,50])
print(arr)
print(arr.ndim)

[10 20 30 40 50]
1


In [28]:
#2D array
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


In [29]:
#3D array
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [30]:
#accessing element from array
arr=np.array([10,20,30,40,50])
print(arr[4])

50


In [31]:
#accessing 2D array
arr=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(arr[0,3])
print(arr[0,-1])

40
50


In [35]:
#slicing
arr=np.array([10,20,30,40,50])
print(arr[1:5])
print(arr[-1:-4])

[20 30 40 50]
[]


In [36]:
#checking shape of an array
arr=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(arr.shape)

(2, 5)


In [37]:
#size of an array
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.size)

10


In [46]:
#reshaping of an array
arr=np.array([1,2,3,4,5,6,7,8,9,10])
newarr=arr.reshape(5,2)
print(newarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [47]:
#iterating array element
arr=np.array([1,2,3,4,5])
for x in arr:
    print(x,2)

1 2
2 2
3 2
4 2
5 2


In [48]:
#concatenate / joining array
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
arr=np.concatenate((arr1,arr2))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [52]:
#splitting array
arr=np.array([1,2,3,4,5,6,7,8,9])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [55]:
#searching an array
arr=np.array([1,2,3,5,4,5])
x=np.where(arr==5)
print(x)

(array([3, 5], dtype=int64),)


In [56]:
#sorting an array
arr=np.array([3,2,0,1])
print(np.sort(arr))
print(np.sort(arr)[::-1])

[0 1 2 3]
[3 2 1 0]


In [61]:
#filtring array
arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
print(newarr)

[41 43]


In [65]:
#conversion of datatype
arr=np.array([1,2,3,4,5])
print(arr.astype(float))

[1. 2. 3. 4. 5.]


In [74]:
arr=np.array([41,42,43,44])

#create an empty list
filter_arr=[]

#go through each element in arr
for element in arr:
    if element>42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [76]:
#adding and removing elements
arr=np.array([1,2,3,4,5])

#append adding only ending of an array
print(np.append(arr,[6,7]))

#insert adding element into specific index
print(np.insert(arr,3,[6,7]))

#delete remove element
print(np.delete(arr,[1]))

#aggregate function
arr=np.array([10,20,30,40,50])

#sum
print(np.sum(arr))

#minimum
print(np.min(arr))

#maximum
print(np.max(arr))

#cumsum
print(np.cumsum(arr))

#statistical function
import statistics as stats
food_prices=[10,20,30,40,50,60,70]
a=np.array(food_prices)

#mean 
print(np.mean(a))

#median
print(np.median(a))

#mode
print(stats.mode(a))

[1 2 3 4 5 6 7]
[1 2 3 6 7 4 5]
[1 3 4 5]
150
10
50
[ 10  30  60 100 150]
40.0
40.0
10
